#!/usr/bin/env bash
# bootstrap.sh — one-shot environment setup for a fresh Ubuntu/Debian cloud server.
#
# Installs system packages (Python 3.11+, Node.js 20, build tools), creates the
# Python virtualenv, installs backend + frontend dependencies, and builds the
# frontend production bundle to frontend/dist.
#
# Idempotent: safe to re-run.
#
# Usage:  bash scripts/bootstrap.sh
#         BACKEND_PORT=8042 FRONTEND_PORT=5215 bash scripts/bootstrap.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

BACKEND_PORT="${BACKEND_PORT:-8042}"
FRONTEND_PORT="${FRONTEND_PORT:-5215}"

log()   { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m[bootstrap]\033[0m %s\n' "$*" >&2; }
die()   { printf '\033[1;31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

# 0. sanity ------------------------------------------------------------------
if [[ "$(uname -s)" != "Linux" ]]; then
  warn "This script targets Linux. Detected $(uname -s); proceeding best-effort."
fi

if ! command -v apt-get >/dev/null 2>&1; then
  die "apt-get not found. Install Python 3.11+, Node.js 20, build-essential manually then re-run from step 'venv'."
fi

SUDO=""
if [[ $EUID -ne 0 ]]; then
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    die "Please re-run as root or install sudo."
  fi
fi

# 1. system packages ---------------------------------------------------------
log "Updating apt index…"
$SUDO apt-get update -y

log "Installing system packages (python, build, curl, git)…"
$SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ca-certificates curl gnupg git build-essential \
  python3 python3-venv python3-pip

# Python version check
PY_VER="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
PY_MAJ="$(python3 -c 'import sys; print(sys.version_info[0])')"
PY_MIN="$(python3 -c 'import sys; print(sys.version_info[1])')"
if (( PY_MAJ < 3 )) || (( PY_MAJ == 3 && PY_MIN < 11 )); then
  warn "Detected python ${PY_VER}. Project requires >=3.11."
  log  "Attempting to install python3.11 from deadsnakes (Ubuntu)…"
  $SUDO apt-get install -y software-properties-common || true
  $SUDO add-apt-repository -y ppa:deadsnakes/ppa || warn "Could not add deadsnakes PPA; continuing."
  $SUDO apt-get update -y || true
  $SUDO apt-get install -y python3.11 python3.11-venv python3.11-dev || \
    die "Could not install python3.11 automatically. Please install it manually."
  PY_BIN="python3.11"
else
  PY_BIN="python3"
fi
log "Using Python interpreter: $($PY_BIN --version)"

# Node.js 20 via NodeSource (only if missing or too old)
NEED_NODE=1
if command -v node >/dev/null 2>&1; then
  NODE_MAJ="$(node -p 'process.versions.node.split(".")[0]')"
  if (( NODE_MAJ >= 18 )); then
    NEED_NODE=0
    log "Detected Node.js $(node -v) (ok)"
  fi
fi
if (( NEED_NODE == 1 )); then
  log "Installing Node.js 20.x via NodeSource…"
  curl -fsSL https://deb.nodesource.com/setup_20.x | $SUDO -E bash -
  $SUDO apt-get install -y nodejs
  log "Node.js installed: $(node -v)"
fi

# 2. Python venv + backend deps ---------------------------------------------
log "Creating Python virtual environment at .venv …"
if [[ ! -d .venv ]]; then
  "$PY_BIN" -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate

log "Upgrading pip / wheel …"
python -m pip install --upgrade pip wheel >/dev/null

log "Installing backend dependencies (editable install of project) …"
pip install -e ".[dev]"

# 3. Frontend deps + build ---------------------------------------------------
log "Installing frontend dependencies …"
cd "$PROJECT_ROOT/frontend"
if [[ -f package-lock.json ]]; then
  npm ci --no-fund --no-audit
else
  npm install --no-fund --no-audit
fi

log "Building frontend production bundle (frontend/dist) …"
npm run build

cd "$PROJECT_ROOT"

# 4. .env scaffold -----------------------------------------------------------
if [[ ! -f .env ]]; then
  log "Writing default .env (mock LLM mode) …"
  cat > .env <<EOF
# Auto-generated by bootstrap.sh — edit and re-deploy as needed.
APP_HOST=0.0.0.0
APP_PORT=${BACKEND_PORT}
LLM_MODE=mock
LOG_LEVEL=INFO
# Comma-separated list of origins allowed to call the backend.
CORS_ORIGINS=http://localhost:${FRONTEND_PORT},http://127.0.0.1:${FRONTEND_PORT}
EOF
fi

if [[ ! -f frontend/.env.local ]]; then
  cat > frontend/.env.local <<EOF
# Leave empty to use the default same-origin /api base URL.
# - Local dev: Vite proxies /api -> http://localhost:${BACKEND_PORT}
# - Nginx deploy: /api can be reverse-proxied to 127.0.0.1:${BACKEND_PORT}
# Set this only when you want the frontend to call a fully qualified backend URL directly.
VITE_API_BASE_URL=
EOF
  log "Wrote frontend/.env.local — rebuild frontend after editing (npm run build)."
fi

mkdir -p .run app_data

cat <<EOF

\033[1;32m[bootstrap]\033[0m Done.

  Backend port  : ${BACKEND_PORT}
  Frontend port : ${FRONTEND_PORT}
  Invite codes  : Chrissy, Ethan  (hard-coded; edit app/api/auth.py to change)

Next:
  bash scripts/deploy.sh           # start both services in the background
  bash scripts/deploy.sh status    # check status
  bash scripts/deploy.sh stop      # stop both services
  bash scripts/deploy.sh logs      # tail logs

EOF
